[project]
name = "fetch-cpy-src"
version = "0.2.0"
description = "Fetch selected part of cpython source repository."
authors = [
    {name = "Alfred DU",email = "ihearmywords@hotmail.com"}
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10, <4"
dependencies = [
    "requests (>=2.32.3,<3.0.0)",
    "pygithub (>=2.6.1,<3.0.0)",
    "tomli (>=2.2.1,<3.0.0)",
    "click (>=8.3.0,<9.0.0)",
]

[project.urls]
Homepage = "https://github.com/phy-precompiler/fetch-cpy-src"
Documentation = "https://fetch-cpy-src.readthedocs.io"
Repository = "https://github.com/phy-precompiler/fetch-cpy-src"
Issues = "https://github.com/phy-precompiler/fetch-cpy-src/issues"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "fetch_cpy_src", from = "src"}]

[tool.poetry.scripts]
fetch-cpy-src = "fetch_cpy_src.cli:main"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
mkdocs = "^1.6.1"
mkdocs-material = "^9.6.22"
pydoc-markdown = "^4.8.2"
tox = "^4.32.0"
pylint = "^4.0.2"
