# this is the cpython source files manifest used by `phy` project
tag = "3.14"


[[items]]
path = 'Grammar/'
type = 'dir'


[[items]]
path = 'Tools/peg_generator/pegen/'
rename = 'pegen/'
type = 'dir'
file_adapters = ['ModAbsImportAdapter']


[[items]]
path = 'Parser/asdl_c.py'
type = 'file'
file_adapters = ['TopLevelScriptImportAdapter']
dir_adapters = ['AddDunderInitAdapter']


[[items]]
path = 'Parser/asdl.py'
type = 'file'
file_adapters = ['TopLevelScriptImportAdapter']


[[items]]
path = 'Parser/Python.asdl'
type = 'file'


[[items]]
path = 'Parser/action_helpers.c'
type = 'file'


[[items]]
path = 'Lib/test/'
type = 'dir'
